########################################
# NF's Picom config — Openbox / Picom 13
########################################

backend = "glx";
vsync = true;
use-damage = true;

# ---------- Shadows ----------
shadow = true;
shadow-radius = 15;
shadow-opacity = 0.65;
shadow-offset-x = -8;
shadow-offset-y = -8;

# ---------- Rounded corners ----------
corner-radius = 12;

# ---------- Fading ----------
fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;
fade-delta = 10;

# ---------- Transparency ----------
inactive-opacity = 0.87;
active-opacity = 0.94;
frame-opacity = 1.0;

detect-client-opacity = true;
detect-rounded-corners = true;

# ---------- Blur ----------
blur-method = "dual_kawase";
blur-strength = 4;
blur-background = true;

blur-background-exclude = [
    "class_g = 'Plank'"
];
# ---------- Detection ----------
detect-transient = true;
